testable:
  - 'src/main/**'
  - 'src/test/**'
  - 'config/checkstyle/**'
  - 'build-tools/checkstyle-rules/**'
  - 'build.gradle'
  - 'settings.gradle'
  - 'gradlew'
  - 'gradlew.bat'
  - 'gradle/**'
  - '.github/workflows/**'
  - '.github/actions/**'
  - '.github/affected-tests/**'
  - '.github/filters.yml'

test_required:
  - 'src/main/**'
  - 'src/test/**'
  - 'build.gradle'
  - 'settings.gradle'
  - 'gradlew'
  - 'gradlew.bat'
  - 'gradle/**'
  - '.github/workflows/**'
  - '.github/actions/**'
  - '.github/affected-tests/**'
  - '.github/filters.yml'

all_tests:
  - 'src/main/java/io/github/metdaisy/amaazon/common/**'
  - 'src/main/java/io/github/metdaisy/amaazon/global/**'
  - 'src/main/java/io/github/metdaisy/amaazon/user/domain/entity/constant/UserRole.java'
  - 'src/main/resources/**'
  - 'src/test/resources/**'
  - 'src/test/java/io/github/metdaisy/amaazon/support/**'
  - 'src/test/java/io/github/metdaisy/amaazon/TestcontainersConfiguration.java'
  - 'src/test/java/io/github/metdaisy/amaazon/AmaazonApplicationTests.java'
  - 'src/test/java/io/github/metdaisy/amaazon/ModularityTest.java'
  - 'build.gradle'
  - 'settings.gradle'
  - 'gradlew'
  - 'gradlew.bat'
  - 'gradle/**'
  - '.github/workflows/**'
  - '.github/actions/**'
  - '.github/affected-tests/**'
  - '.github/filters.yml'
