spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  flyway:
    enabled: false
    baseline-on-migrate: false
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

logging:
  file:
    name: .logs/amaazon.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      clean-history-on-start: true
      max-history: 30
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %clr(%-5level) [traceId: %.-8X{traceId}] [%logger{0}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId: %X{traceId}] [%logger{0}] - %msg%n"
