caffeine.jcache {
  default {
    store-by-value.enabled = false
  }
  Category {
    policy {
      maximum.size = 100
      eager-expiration.after-write = 12h
    }
  }
  Tag {
    policy {
      maximum.size = 1000
      eager-expiration.after-write = 6h
    }
  }
}
