spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  flyway:
    enabled: false
    baseline-on-migrate: false
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

amaazon:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    guest-expiration: ${JWT_GUEST_TOKEN_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
    refresh:
      cookie:
        name: REFRESH_TOKEN
        path: /
        same-site: Lax
        secure: false
  cache:
    type: ${CACHE_TYPE} # caffeine | redis
    capacity: ${CACHE_CAPACITY}

logging:
  file:
    name: .logs/amaazon.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      clean-history-on-start: true
      max-history: 30
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %clr(%-5level) [requestId: %.-8X{requestId}] [%X{requestMethod}] %X{requestUri} [%logger{0}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [requestId: %X{requestId}] [%X{requestMethod}] %X{requestUri} [%logger{0}] - %msg%n"
