name: Test - Domain slice

on:
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      test-scope:
        required: true
        type: string
      test-patterns:
        required: false
        type: string
        default: '[]'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run ${{ inputs.test-name }} tests
        uses: ./.github/actions/run-domain-test
        with:
          test-name: ${{ inputs['test-name'] }}
          test-scope: ${{ inputs['test-scope'] }}
          test-patterns: ${{ inputs['test-patterns'] }}
