name: OpenGrep Code Quality Review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  opengrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OpenGrep (Best Practices & Code Smells)
        uses: platform-sec/opengrep-action@main
        with:
          patterns: ''
          target: src
          config: "p/java p/spring"
          strict: false
